services:
  loader:
    image: loader
    container_name: loader
    build:
      context: ./containers/loader/
    environment:
      WAREHOUSE_USER: ${WAREHOUSE_USER}
      WAREHOUSE_PASSWORD: ${WAREHOUSE_PASSWORD}
      WAREHOUSE_DB: ${WAREHOUSE_DB}
      WAREHOUSE_HOST: ${WAREHOUSE_HOST}
      WAREHOUSE_PORT: ${WAREHOUSE_PORT}
      PREFECT_API_KEY: ${PREFECT_API_KEY}
      PREFECT_WS: ${PREFECT_WS}
    volumes:
      - .:/opt/sde
    command: >
      bash -c "prefect cloud workspace set --workspace ${PREFECT_WS}
      && tail -f /dev/null"
    

  warehouse:
    image: postgres:14.7-alpine
    restart: always
    environment:
      POSTGRES_USER: ${WAREHOUSE_USER}
      POSTGRES_PASSWORD: ${WAREHOUSE_PASSWORD}
      POSTGRES_DB: ${WAREHOUSE_DB}
    volumes:
      - ./containers/warehouse:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    expose:
      - 5432